### ISSUE TITLE
Reactive Forms broken in Version 10 of angular-redux/forms

### ISSUE THREAD

**Issue by Ebg-Bibi** [angular-redux/platform#91] opened 2019-06-25 08:23 UTC
### This is a...

- [ ] feature request
- [x ] bug report
- [ ] usage question

The "ReactiveConnectDirective" extends ConnectBase but does not set the protected field "form" anymore.

In Version 9 the Input property formGroup in "ReactiveConnect" is declared as:

 @Input('formGroup') form: any;

In Version 10 it is declared as:

@Input() formGroup: any;

So ConnectBase.form is no longer set to the formGroup attributes value.

This breaks ConnectBase.resetState which is called from ConnectBase.ngAfterContentInit:

const formElement =
      this.form.control === undefined ? this.form : this.form.control;

this.form is undefined and accessing control causes an error.

**Comment by smithad15** [comment] 2019-07-07 23:16
Duplicate of #85

**Closed by smithad15** 2019-07-07 23:16 UTC
Labels: bug, duplicate, pkg: form
